micronaut.application.name=catalog-service
micronaut.server.port=${CATALOG_PORT:8081}

endpoints.health.enabled=true
endpoints.health.sensitive=false

micronaut.router.versioning.enabled=true

micronaut.router.versioning.header.enabled=true
micronaut.router.versioning.header.names[0]=X-API-VERSION
micronaut.router.versioning.header.names[1]=X-VERSION
micronaut.router.versioning.header.names[2]=VERSION

micronaut.router.versioning.parameter.enabled=false
